apiVersion: skaffold/v1
kind: Config
metadata:
  name: dreamdrugs
build:
  local: {}
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/dreamdrugs/backend
    context: backend
    sync:
      infer:
      - 'app.py'
      - 'dreamdrugs/**/*.py'

  - image: gcr.io/dreamdrugs/frontend
    context: frontend
    sync:
      infer:
      - 'src/**/*'
      - 'server.js'
# Until skaffold doesn't support helm 3, let's use this user's build:
#
#   https://github.com/GoogleContainerTools/skaffold/issues/2142#issuecomment-570615439
#
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: deploy/dreamdrugs
      values:
        backendImage: gcr.io/dreamdrugs/backend
        frontendImage: gcr.io/dreamdrugs/frontend
      setValues:
        development: true
      overrides:
        redis:
          password: pass1234
