name: CI

on:
  push:
    branches:
      - '*'  # Consider using [main] or [**] instead depending on your intent

jobs:
  build-test-coverage:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Run backend tests
      run: docker-compose run backend sh -c 'pytest --cov=dreamdrugs --cov-report xml'

    - name: Run frontend tests
      run: docker-compose run frontend sh -c 'yarn test:coverage'

    - name: Upload test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

